using UnityEngine;
using System.Collections;


static public class DBs
{
    static public string[][] DB1 = new string[][]
    {
    new string[]{"cama,cama" },
    new string[]{"coche,coche" },
    new string[]{"dedo,dedo" },
    new string[]{"brazo,brazo" },
    new string[]{"crema,crema"},
    new string[]{"fruta,fruta"},
    new string[]{"plato,plato"},
    new string[]{"babero,babero"},
    new string[]{"papaya,papaya"},
    new string[]{"camisa,camisa"},
    new string[]{"brocoli,brocoli"},
    new string[]{"croqueta,croqueta"},
    new string[]{"platano,platano"},
    new string[]{"frutero,frutero"},
    new string[]{"cama,cama"},
    new string[]{"coche,coche"},
    new string[]{"dedo,dedo"},
    new string[]{"brazo,brazo"},
    new string[]{"crema,crema"},
    new string[]{"fruta,fruta"},
    new string[]{"plato,plato"},
    new string[]{"babero,babero"},
    new string[]{"papaya,papaya"},
    new string[]{"camisa,camisa"},
    new string[]{"brocoli,brocoli"},
    new string[]{"croqueta,croqueta"},
    new string[]{"platano,platano"},
    new string[]{"frutero,frutero"},
    new string[]{"cama,cama"},
    new string[]{"coche,coche"},
    new string[]{"dedo,dedo"},
    new string[]{"brazo,brazo"},
    new string[]{"crema,crema"},
    new string[]{"fruta,fruta"},
    new string[]{"plato,plato"},
    new string[]{"babero,babero"},
    new string[]{"papaya,papaya"},
    new string[]{"camisa,camisa"},
    new string[]{"brocoli,brocoli"},
    new string[]{"croqueta,croqueta"},
    new string[]{"platano,platano"},
    new string[]{"frutero,frutero"},
    new string[]{"cama,cama"},
    new string[]{"coche,coche"},
    new string[]{"dedo,dedo"},
    new string[]{"brazo,brazo"},
    new string[]{"crema,crema"},
    new string[]{"fruta,fruta"},
    new string[]{"plato,plato"},
    new string[]{"babero,babero"},
    new string[]{"papaya,papaya"},
    new string[]{"camisa,camisa"},
    new string[]{"brocoli,brocoli"},
    new string[]{"croqueta,croqueta"},
    new string[]{"platano,platano"},
    new string[]{"frutero,frutero"},
    new string[]{"cama,cama"},
    new string[]{"coche,coche"},
    new string[]{"dedo,dedo"},
    new string[]{"brazo,brazo"},
    new string[]{"crema,crema"},
    new string[]{"fruta,fruta"},
    new string[]{"plato,plato"},
    new string[]{"babero,babero"},
    new string[]{"papaya,papaya"},
    new string[]{"camisa,camisa"},
    new string[]{"brocoli,brocoli"},
    new string[]{"croqueta,croqueta"},
    new string[]{"platano,platano"},
    new string[]{"frutero,frutero"},
    new string[]{"cama,cama"},
    new string[]{"coche,coche"},
    new string[]{"dedo,dedo"},
    new string[]{"brazo,brazo"},
    new string[]{"crema,crema"},
    new string[]{"fruta,fruta"},
    new string[]{"plato,plato"},
    new string[]{"babero,babero"},
    new string[]{"papaya,papaya"},
    new string[]{"camisa,camisa"},
    new string[]{"brocoli,brocoli"},
    new string[]{"croqueta,croqueta"},
    new string[]{"platano,platano"},
    new string[]{"frutero,frutero"},
    new string[]{"gato,gato"},
    new string[]{"mano,mano"},
    new string[]{"mesa,mesa"},
    new string[]{"pato,pato"},
    new string[]{"vaca,vaca"},
    new string[]{"mosca,mosca"},
    new string[]{"colcha,colcha"},
    new string[]{"parque,parque"},
    new string[]{"torta,torta"},
    new string[]{"galleta,galleta"},
    new string[]{"juguete,juguete"},
    new string[]{"mamila,mamila"},
    new string[]{"musica,musica"},
    new string[]{"pelota,pelota"},
    new string[]{"fabrica,fabrica"},
    new string[]{"pescado,pescado"},
    new string[]{"ventana,ventana"},
    new string[]{"tortilla,tortilla"},
    new string[]{"gato,gato"},
    new string[]{"mano,mano"},
    new string[]{"mesa,mesa"},
    new string[]{"pato,pato"},
    new string[]{"vaca,vaca"},
    new string[]{"mosca,mosca"},
    new string[]{"colcha,colcha"},
    new string[]{"parque,parque"},
    new string[]{"torta,torta"},
    new string[]{"galleta,galleta"},
    new string[]{"juguete,juguete"},
    new string[]{"mamila,mamila"},
    new string[]{"musica,musica"},
    new string[]{"pelota,pelota"},
    new string[]{"fabrica,fabrica"},
    new string[]{"pescado,pescado"},
    new string[]{"ventana,ventana"},
    new string[]{"tortilla,tortilla"},
    new string[]{"gato,gato"},
    new string[]{"mano,mano"},
    new string[]{"mesa,mesa"},
    new string[]{"pato,pato"},
    new string[]{"vaca,vaca"},
    new string[]{"mosca,mosca"},
    new string[]{"colcha,colcha"},
    new string[]{"parque,parque"},
    new string[]{"torta,torta"},
    new string[]{"galleta,galleta"},
    new string[]{"juguete,juguete"},
    new string[]{"mamila,mamila"},
    new string[]{"musica,musica"},
    new string[]{"pelota,pelota"},
    new string[]{"fabrica,fabrica"},
    new string[]{"pescado,pescado"},
    new string[]{"ventana,ventana"},
    new string[]{"tortilla,tortilla"},
    new string[]{"gato,gato"},
    new string[]{"mano,mano"},
    new string[]{"mesa,mesa"},
    new string[]{"pato,pato"},
    new string[]{"vaca,vaca"},
    new string[]{"mosca,mosca"},
    new string[]{"colcha,colcha"},
    new string[]{"parque,parque"},
    new string[]{"torta,torta"},
    new string[]{"galleta,galleta"},
    new string[]{"juguete,juguete"},
    new string[]{"mamila,mamila"},
    new string[]{"musica,musica"},
    new string[]{"pelota,pelota"},
    new string[]{"fabrica,fabrica"},
    new string[]{"pescado,pescado"},
    new string[]{"ventana,ventana"},
    new string[]{"tortilla,tortilla"},
    new string[]{"gato,gato"},
    new string[]{"mano,mano"},
    new string[]{"mesa,mesa"},
    new string[]{"pato,pato"},
    new string[]{"vaca,vaca"},
    new string[]{"mosca,mosca"},
    new string[]{"colcha,colcha"},
    new string[]{"parque,parque"},
    new string[]{"torta,torta"},
    new string[]{"galleta,galleta"},
    new string[]{"juguete,juguete"},
    new string[]{"mamila,mamila"},
    new string[]{"musica,musica"},
    new string[]{"pelota,pelota"},
    new string[]{"fabrica,fabrica"},
    new string[]{"pescado,pescado"},
    new string[]{"ventana,ventana"},
    new string[]{"tortilla,tortilla"},
    new string[]{"gato,gato"},
    new string[]{"mano,mano"},
    new string[]{"mesa,mesa"},
    new string[]{"pato,pato"},
    new string[]{"vaca,vaca"},
    new string[]{"mosca,mosca"},
    new string[]{"colcha,colcha"},
    new string[]{"parque,parque"},
    new string[]{"torta,torta"},
    new string[]{"galleta,galleta"},
    new string[]{"juguete,juguete"},
    new string[]{"mamila,mamila"},
    new string[]{"musica,musica"},
    new string[]{"pelota,pelota"},
    new string[]{"fabrica,fabrica"},
    new string[]{"pescado,pescado"},
    new string[]{"ventana,ventana"},
    new string[]{"tortilla,tortilla"},

    };


    static public string[][] DB2 = new string[][]
    {
    new string[]{"gato,gafo"},
    new string[]{"mesa,meba"},
    new string[]{"vaca,vama"},
    new string[]{"mosca,josca"},
    new string[]{"colcha,rolcha"},
    new string[]{"parque,larque"},
    new string[]{"torta,morta"},
    new string[]{"galleta,salleta"},
    new string[]{"juguete,buguete"},
    new string[]{"mamila,tamila"},
    new string[]{"musica,susica"},
    new string[]{"pelota,nelota"},
    new string[]{"fabrica,fabrima"},
    new string[]{"pescado,pescafo"},
    new string[]{"tortilla,torticha"},
    new string[]{"gato,sato"},
    new string[]{"mano,tano"},
    new string[]{"mesa,jesa"},
    new string[]{"pato,lato"},
    new string[]{"vaca,jaca"},
    new string[]{"fabrica,gabrica"},
    new string[]{"pescado,rescado"},
    new string[]{"ventana,sentana"},
    new string[]{"brazo,krazo"},
    new string[]{"crema,drema"},
    new string[]{"fruta,druta"},
    new string[]{"plato,clato"},
    new string[]{"babero,sabero"},
    new string[]{"papaya,lapaya"},
    new string[]{"brocoli,brocoki"},
    new string[]{"cama,nama"},
    new string[]{"coche,loche"},
    new string[]{"dedo,jedo"},
    new string[]{"brocoli,Krocoli"},
    new string[]{"croqueta,droqueta"},
    new string[]{"platano,llatano"},
    new string[]{"frutero,grutero"},
    };

    static public string[][] DB3 = new string[][]
    {
    new string[]{"mano,mapo"},
    new string[]{"pato,pamo"},
    new string[]{"ventana,ventapa"},
    new string[]{"mosca,mosma"},
    new string[]{"colcha,colba"},
    new string[]{"parque,parme"},
    new string[]{"torta,torma"},
    new string[]{"galleta,gallema"},
    new string[]{"juguete,jugueñe"},
    new string[]{"mamila,mamija"},
    new string[]{"musica,musima"},
    new string[]{"pelota,peloña"},
    new string[]{"cama,cata"},
    new string[]{"coche,cobe"},
    new string[]{"dedo,defo"},
    new string[]{"croqueta,croqueña"},
    new string[]{"platano,platafo"},
    new string[]{"frutero,fruteco"},
    new string[]{"brazo,brallo"},
    new string[]{"crema,creka"},
    new string[]{"fruta,fruma"},
    new string[]{"plato,plamo"},
    new string[]{"babero,babepo"},
    new string[]{"papaya,papasa"},
    new string[]{"camisa,camiba"},

    };

    
    static public string[][] DB4 = new string[][]
    {
    new string[]{"gato,jato"},
    new string[]{"mano,fano"},
    new string[]{"mesa,lesa"},
    new string[]{"pato,jato"},
    new string[]{"vaca,faca"},
    new string[]{"mosca,losca"},
    new string[]{"colcha,bolcha"},
    new string[]{"parque,garque"},
    new string[]{"torta,jorta"},
    new string[]{"galleta,malleta"},
    new string[]{"juguete,puguete"},
    new string[]{"mamila,pamila"},
    new string[]{"musica,gusica"},
    new string[]{"pelota,melota"},
    new string[]{"fabrica,babrica"},
    new string[]{"pescado,mescado"},
    new string[]{"ventana,kentana"},
    new string[]{"tortilla,bortilla"},
    new string[]{"tortilla,bortilla"},
    new string[]{"cama,sama"},
    new string[]{"coche,soche"},
    new string[]{"dedo,medo"},
    new string[]{"brazo,frazo"},
    new string[]{"crema,brema"},
    new string[]{"fruta,kruta"},
    new string[]{"plato,glato"},
    new string[]{"babero,fabero"},
    new string[]{"papaya,mapaya"},
    new string[]{"camisa,bamisa"},
    new string[]{"brocoli,trocoli"},
    new string[]{"croqueta,broqueta"},
    new string[]{"platano,glatano"},
    new string[]{"frutero,crutero"},
    new string[]{"camisa,bamisa"},
    };

    static public string[][] DB5 = new string[][]
    {
    new string[]{"gato,garo"},
    new string[]{"mano,mabo"},
    new string[]{"mesa,meda"},
    new string[]{"pato,pafo"},
    new string[]{"vaca,vasa"},
    new string[]{"mosca,mosba"},
    new string[]{"colcha,colca"},
    new string[]{"parque,parñe"},
    new string[]{"torta,torja"},
    new string[]{"galleta,galleja"},
    new string[]{"juguete,juguene"},
    new string[]{"mamila,mamima"},
    new string[]{"musica,musiba"},
    new string[]{"pelota,peloba"},
    new string[]{"fabrica,fabrisa"},
    new string[]{"pescado,pescaso"},
    new string[]{"ventana,ventasa"},
    new string[]{"tortilla,tortida"},
    new string[]{"cama,carra"},
    new string[]{"coche,cone"},
    new string[]{"dedo,decho"},
    new string[]{"brazo,brado"},
    new string[]{"crema,crefa"},
    new string[]{"fruta,frufa"},
    new string[]{"plato,plafo"},
    new string[]{"babero,babemo"},
    new string[]{"papaya,papaja"},
    new string[]{"camisa,camida"},
    new string[]{"brocoli,brocoji"},
    new string[]{"croqueta,croquela"},
    new string[]{"platano,plataso"},
    new string[]{"frutero,fruteso"},

    };

    static public string[][] DB6 = new string[][]
    {
    new string[]{"gato,llato"},
    new string[]{"mano,pano"},
    new string[]{"mesa,fesa"},
    new string[]{"pato,fato"},
    new string[]{"vaca,gaca"},
    new string[]{"mosca,nosca"},
    new string[]{"colcha,polcha"},
    new string[]{"parque,barque"},
    new string[]{"torta,dorta"},
    new string[]{"galleta,balleta"},
    new string[]{"juguete,fuguete"},
    new string[]{"mamila,namila"},
    new string[]{"musica,busica"},
    new string[]{"pelota,belota"},
    new string[]{"fabrica,chabrica"},
    new string[]{"pescado,fescado"},
    new string[]{"ventana,mentana"},
    new string[]{"tortilla,dortilla"},
    new string[]{"cama,pama"},
    new string[]{"coche,joche"},
    new string[]{"dedo,gedo"},
    new string[]{"brazo,draso"},
    new string[]{"crema,trema"},
    new string[]{"fruta,pruta"},
    new string[]{"plato,blato"},
    new string[]{"babero,dabero"},
    new string[]{"papaya,bapaya"},
    new string[]{"camisa,jamisa"},
    new string[]{"brocoli,grocoli"},
    new string[]{"croqueta,proqueta"},
    new string[]{"platano,klatano"},
    new string[]{"frutero,prutero"},

    };

    static public string[][] DB7 = new string[][]
    {
    new string[]{"gato,gado"},
    new string[]{"mano,maro"},
    new string[]{"mesa,mefa"},
    new string[]{"pato,pado"},
    new string[]{"vaca,vapa"},
    new string[]{"mosca,mosta"},
    new string[]{"colcha,colta"},
    new string[]{"parque,parpe"},
    new string[]{"torta,torda"},
    new string[]{"galleta,gallepa"},
    new string[]{"juguete,juguepe"},
    new string[]{"mamila,mamira"},
    new string[]{"musica,musija"},
    new string[]{"pelota,pelopa"},
    new string[]{"fabrica,fabrija"},
    new string[]{"pescado,pescabo"},
    new string[]{"ventana,ventaña"},
    new string[]{"tortilla,tortiña"},
    new string[]{"cama,cafa"},
    new string[]{"coche,cofe"},
    new string[]{"dedo,dego"},
    new string[]{"brazo,brafo"},
    new string[]{"crema,crena"},
    new string[]{"fruta,fruda"},
    new string[]{"plato,plado"},
    new string[]{"babero,babeno"},
    new string[]{"papaya,papala"},
    new string[]{"camisa,camija"},
    new string[]{"brocol,brocolli"},
    new string[]{"croqueta,croquepa"},
    new string[]{"platano,platamo"},
    new string[]{"frutero,fruteno"},

    };





    static public AudioClip[][] DB1Audio = new AudioClip[][]
    {




    };
}
